export const ADD_LINKS_DATA_ENTRY_SUCCESS = 'ADD_LINKS_DATA_ENTRY_SUCCESS';
export const ADD_LINKS_DATA_ENTRY_FAILURE = 'ADD_LINKS_DATA_ENTRY_FAILURE';

// TODO: rename all this stuff into FETCH_LINKS_SOMETHING
export const UPDATE_LINKS_DATA = 'UPDATE_LINKS_DATA';
export const UPDATE_LINKS_DATA_SUCCESS = 'UPDATE_LINKS_DATA_SUCCESS';
export const UPDATE_LINKS_DATA_FAILURE = 'UPDATE_LINKS_DATA_FAILURE';

export const CLEAR_LINKS_DATA = 'CLEAR_LINKS_DATA';