export const ADD_LINKS_DATA_ENTRY_SUCCESS = 'ADD_LINKS_DATA_ENTRY_SUCCESS';
export const ADD_LINKS_DATA_ENTRY_FAILURE = 'ADD_LINKS_DATA_ENTRY_FAILURE';

export const UPDATE_LINKS_DATA = 'UPDATE_LINKS_DATA';

export const CLEAR_LINKS_DATA = 'CLEAR_LINKS_DATA';