export const ADD_SHORTCODE_SUCCESS = 'ADD_SHORTCODE_SUCCESS';
export const ADD_SHORTCODE_FAILURE = 'ADD_SHORTCODE_FAILURE';

export const UPDATE_LINKS_INFO = 'UPDATE_LINKS_INFO';

export const CLEAR_HISTORY = 'CLEAR_HISTORY';